version: "3.8"

services:
  grwebide-db:
    image: mysql:8.0
    container_name: grwebide-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - grwebide-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - grwebide-net

  grwebide-spring:
    image: ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest
    container_name: grwebide-spring
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      EXECUTION_WORK_DIR: /tmp/compiler-exec
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/compiler-exec:/tmp/compiler-exec
    networks:
      - grwebide-net

  grwebide-redis:
    image: redis:7-alpine
    container_name: grwebide-redis
    restart: unless-stopped
    volumes:
      - grwebide-redis-data:/data
    networks:
      - grwebide-net

volumes:
  grwebide-db-data:
  grwebide-redis-data:

networks:
  grwebide-net:
    external: true