package com.example.demo.execution.config;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.servers.Server;
import org.springframework.context.annotation.Configuration;

@Configuration
@OpenAPIDefinition(
	info = @Info(
		title = "DeepFlow-WebIDE API",
		version = "v1",
		description = "DeepFlow 팀-WebIDE 프로젝트 API 명세서입니다.\n"
				+ "Java/Python 코드를 Docker 컨테이너에서 실행하는 API이며 REST /compile은 사용하지 않고 WebSocket만 지원합니다.\n\n"
				+ "### 인증\n"
				+ "- 로그인 후 발급받은 JWT를 요청에 포함해야 합니다.\n"
				+ "- WebSocket 핸드셰이크 요청 헤더에 Authorization: Bearer <token> 을 넣습니다.\n\n"
				+ "## 코드 실행 WebSocket 사용법\n"
				+ "1) ws://localhost:8080/ws/compile 로 WebSocket 연결을 엽니다.\n"
				+ "2) 연결이 열린 뒤 start 메시지로 실행을 요청합니다.\n"
				+ "3) 실행 중 출력은 output 메시지로 스트리밍됩니다.\n"
				+ "4) 실행 종료 시 result 메시지가 도착합니다.\n"
				+ "5) 입력이 필요하면 input 메시지로 전달합니다.\n\n"
				+ "### 요청 메시지\n"
				+ "- start: {\"type\":\"start\",\"code\":\"...\",\"language\":\"java|python\",\"params\":[...]}\n"
				+ "  - code: 실행할 소스 코드\n"
				+ "  - language: java | python\n"
				+ "  - params: argv 배열\n"
				+ "- input: {\"type\":\"input\",\"data\":\"...\"}\n"
				+ "- stop: {\"type\":\"stop\"}\n\n"
				+ "### 응답 메시지\n"
				+ "- output: {\"type\":\"output\",\"stream\":\"stdout|stderr\",\"data\":\"...\"}\n"
				+ "  - stream: stdout | stderr\n"
				+ "  - data: 출력 데이터 (스트리밍)\n"
				+ "- result: {\"type\":\"result\",\"result\":\"성공|실패\",\"stdout\":\"...\",\"stderr\":\"...\",\"exitCode\":0,\"SystemOut\":\"...\",\"performance\":123,\"stage\":\"run\"}\n"
				+ "  - result: 성공 | 실패\n"
				+ "  - stdout: 표준 출력\n"
				+ "  - stderr: 표준 에러\n"
				+ "  - exitCode: 종료 코드\n"
				+ "  - SystemOut: 호환용 출력 필드\n"
				+ "  - performance: 실행 시간(ms)\n"
				+ "  - stage: run\n"
				+ "- error: {\"type\":\"error\",\"message\":\"...\"}\n"
				+ "  - message: 오류 메시지\n\n"
				+ "## 실시간 협업 에디터 WebSocket 사용법\n"
				+ "1) ws://localhost:8080/ws/editor/{fileId}?token={jwtToken} 로 WebSocket 연결을 엽니다.\n"
				+ "  - fileId: 편집할 파일 ID\n"
				+ "  - token: JWT 인증 토큰 (쿼리 파라미터)\n"
				+ "2) 연결이 열린 뒤 같은 파일을 편집하는 다른 사용자들과 실시간으로 동기화됩니다.\n"
				+ "3) 텍스트 변경 시 TEXT_CHANGE 메시지를 서버로 전송합니다.\n"
				+ "4) 서버는 변경 사항을 계산하여 TEXT_SYNC 메시지로 모든 클라이언트에 브로드캐스트합니다.\n"
				+ "5) 커서 이동 시 CURSOR_MOVE 메시지를 전송하여 다른 사용자의 커서 위치를 공유합니다.\n\n"
				+ "### 버전 관리\n"
				+ "- 각 파일은 버전 번호를 가지며, 텍스트 변경 시마다 버전이 증가합니다.\n"
				+ "- 클라이언트가 보낸 버전이 서버의 최신 버전보다 낮으면 해당 변경사항은 무시됩니다.\n"
				+ "- 버전 충돌 시 클라이언트는 최신 파일 내용을 다시 요청해야 합니다.\n\n"
				+ "### 클라이언트 → 서버 메시지\n"
				+ "- TEXT_CHANGE: {\"type\":\"TEXT_CHANGE\",\"fileId\":123,\"userId\":1,\"content\":\"...\",\"version\":5}\n"
				+ "  - type: TEXT_CHANGE\n"
				+ "  - fileId: 편집 중인 파일 ID\n"
				+ "  - userId: 사용자 ID\n"
				+ "  - content: 변경된 전체 텍스트 내용\n"
				+ "  - version: 클라이언트가 알고 있는 파일 버전\n"
				+ "- CURSOR_MOVE: {\"type\":\"CURSOR_MOVE\",\"fileId\":123,\"userId\":1,\"cursor\":{\"line\":10,\"column\":5}}\n"
				+ "  - type: CURSOR_MOVE\n"
				+ "  - fileId: 편집 중인 파일 ID\n"
				+ "  - userId: 사용자 ID\n"
				+ "  - cursor: 커서 위치 정보\n"
				+ "    - line: 줄 번호 (0부터 시작)\n"
				+ "    - column: 열 번호 (0부터 시작)\n\n"
				+ "### 서버 → 클라이언트 메시지\n"
				+ "- TEXT_SYNC: {\"type\":\"TEXT_SYNC\",\"fileId\":123,\"userId\":1,\"version\":6,\"change\":{\"range\":{\"start\":10,\"end\":15},\"newText\":\"새로운 텍스트\"}}\n"
				+ "  - type: TEXT_SYNC\n"
				+ "  - fileId: 편집 중인 파일 ID\n"
				+ "  - userId: 변경을 수행한 사용자 ID\n"
				+ "  - version: 최신 파일 버전\n"
				+ "  - change: 변경 사항 (delta)\n"
				+ "    - range: 변경 범위\n"
				+ "      - start: 변경 시작 위치 (0부터 시작)\n"
				+ "      - end: 변경 끝 위치\n"
				+ "    - newText: 새로 삽입/교체할 텍스트 (삭제의 경우 빈 문자열)\n"
				+ "- CURSOR_MOVE: {\"type\":\"CURSOR_MOVE\",\"fileId\":123,\"userId\":2,\"cursor\":{\"line\":10,\"column\":5}}\n"
				+ "  - type: CURSOR_MOVE\n"
				+ "  - fileId: 편집 중인 파일 ID\n"
				+ "  - userId: 커서를 이동한 사용자 ID\n"
				+ "  - cursor: 커서 위치 정보\n"
				+ "    - line: 줄 번호 (0부터 시작)\n"
				+ "    - column: 열 번호 (0부터 시작)\n\n"
				+ "### 동작 방식\n"
				+ "- 서버는 TEXT_CHANGE 메시지를 받으면 전체 텍스트를 DB에 저장하고, 이전 버전과 비교하여 변경 사항(delta)만 계산합니다.\n"
				+ "- 계산된 변경 사항은 같은 파일을 편집하는 모든 클라이언트에게 TEXT_SYNC 메시지로 브로드캐스트됩니다.\n"
				+ "- 클라이언트는 TEXT_SYNC 메시지를 받아 로컬 텍스트에 변경 사항을 적용하여 동기화합니다.\n"
				+ "- CURSOR_MOVE 메시지는 DB에 저장되지 않으며, 같은 파일을 편집하는 다른 사용자들에게만 실시간으로 전달됩니다."
	),
	servers = {
		@Server(url = "https://t2.mobidic.shop", description = "배포 서버"),
		@Server(url = "http://localhost:8080", description = "로컬 개발 서버")
	}
)
public class OpenApiConfig {}
